name: Update badges

on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  credly-badges:
    name: "Update README with Credly badges"
    runs-on: ubuntu-latest

    steps:
      - name: Update
        uses: mikejoh/credly-badges@main
        with:
          CREDLY_USERNAME: chris-cui.645a2d96
          COMMIT_MESSAGE: "Update Credly badges!"
